
version: 1.0.0
app:
  name: Acuity Backstage
  baseUrl: http://localhost:3000

api:
  name: bkstg-api
  namespace: bkstg
  port: 8000
  baseUrl: http://localhost:8000
  registry: AcuityBkstgAcrSR.azurecr.io
  imageRepository: bkstg-main-eastus-api
  releaseTag: main-2ba5de9
  database:
    client: sqlite3
    connection: ':memory:'
  cache:
    store: memory
  # hpa
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress-nginx:
  namespace: ingress
  controller:
    replicaCount: 2
    nodeSelector: 
      "beta.kubernetes.io/os": linux
  defaultBackend:
    nodeSelector: 
      "beta.kubernetes.io/os": linux

cert-manager:
  namespace: cert-mngr
